### ISSUE TITLE
Black screen at bottom in landscape mode

### ISSUE THREAD

**Issue by anupamkgit** [hackiftekhar/IQKeyboardManager#1058] opened 2017-10-11 12:22 UTC
Hi,
similar issue : https://github.com/hackiftekhar/IQKeyboardManager/issues/331

I am using the IQKeyboardManagerSwift latest version I am having issue black screen at bottom --> When I tap on text field in landscape mode of device  keyboard comes up and view of controller and background image goes up  black screen of window can be seen at bottom View does not come back to original position after keyboard dismiss.

I want to move container view of the text field up, not the view of the controller and background image, the container view is horizontally and vertically center in auto layout.  I tried to add IQLayoutGuideConstraint to container view but no luck. it would be great if you can provide some information to achieve it.  please seen storyboard screenshot below

 
![screen shot 2017-10-11 at 5 44 34 pm](https://user-images.githubusercontent.com/32706023/31440119-672d7e94-aeac-11e7-93b9-2ed5fbd18c7c.png)

below is the screenshot of the device stepwise.

![screen shot 2017-10-11 at 6 01 41 pm](https://user-images.githubusercontent.com/32706023/31440857-fdafe332-aeae-11e7-9d15-009f5453cfc7.png)

![screen shot 2017-10-11 at 6 02 12 pm](https://user-images.githubusercontent.com/32706023/31440881-08201788-aeaf-11e7-9fbc-15a9501a97d5.png)

![screen shot 2017-10-11 at 6 02 52 pm](https://user-images.githubusercontent.com/32706023/31440890-0fc4f71a-aeaf-11e7-8312-0060445c466a.png)

**Comment by mohammad2015** [comment] 2017-10-12 14:05
I am also having the same issue

**Comment by anupamkgit** [comment] 2017-10-12 16:04
@hackiftekhar Please help us.

**Comment by hackiftekhar** [comment] 2017-10-12 18:30
Can you please check if you pinned any constraint with top layout guide or bottom layout guide or safe area?

**Comment by mohammad2015** [comment] 2017-10-12 22:04
no

**Comment by anupamkgit** [comment] 2017-10-13 08:39
@hackiftekhar I have not pinned any constraint with top layout guide or bottom layout guide or safe area please seen below snapshot 

![screen shot 2017-10-13 at 2 07 27 pm](https://user-images.githubusercontent.com/32706023/31537529-20d6730e-b020-11e7-868a-dffc165cc361.png)

**Comment by mohammad2015** [comment] 2017-10-13 14:29
Please help us  i want upload app in iOS store @hackiftekhar

**Comment by hackiftekhar** [comment] 2017-10-25 18:54
@mohammad2015 @anupamkgit your configuration looks simple and shouldn't be an issue. Can you please share a demo application to reproduce this issue so that I can debug it?

**Comment by anupamkgit** [comment] 2017-11-06 10:18
@hackiftekhar please find my iPad demo app file below.
** issues are explained below, Please suggest me how can I fixe these issues-** 
[Demo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1445794/Demo.zip)

1)  Here is how things are (On the first Screen ) : 

- I have a view containing my form,

- The view is centered horizontally and vertically

- In portrait, the keyboard pops up and does not hide the view

- In landscape, the keyboard pops up and does hide the view

Order of things :

1. Start from Landscape
2. Select a text field (Activation field on the first screen)
3. (Keyboard pops up)
4. Rotate to portrait
5. Press done
6. (Keyboard hides)
7. Result: window black screen at bottom 


2) Once you click on Activate button Here is things are (On the second screen)

- I have a table view that is placed at bottom and starts from middle,

- the table is pin to all side and table cell contains a text field, 

- in portrait, keyboard pops up and table does hide the table but not completely 

- In landscape, keyboard pops up and table does hide the table completely 

2.1) in Landscape mode 

1. select the text field of the table view 
2. (Keyboard pops up)
3. Result: table does scroll but user can not see the text field as table is fully covered by keyboard


2.2) I the  portrait  mode

1. select the text field of table view  
2. Result: working fine As table is visible after keyboard pops up so user can see the text filed. 

2.3) When user switch orientation on second screen Order of things :

1. Start from portrait
2. Select a text field of table view 
3. (Keyboard pops up)
4. Rotate to landscape
5. Press done
6. (Keyboard hides)
7. Result: the frame of table got changed

**Comment by hackiftekhar** [comment] 2017-11-08 06:42
Thanks @anupamkgit, I’m surely take a look when I get some free time.

**Comment by hackiftekhar** [comment] 2017-11-19 16:48
I got what's the issue, it's because there is notifications are firing in different order in iPad and iPhone.

**iPad**
willChangeStatusBarOrientation
didChangeStatusBarFrame
keyboardWillHide
keyboardDidHide
keyboardWillShow
keyboardDidShow

**iPhone**
willChangeStatusBarOrientation
keyboardWillHide
keyboardDidHide
didChangeStatusBarFrame
keyboardWillShow
keyboardDidShow
keyboardWillShow
keyboardDidShow

It might take time to fix this issue since there are common logic for both devices.

**Comment by wtkeller** [comment] 2018-02-22 21:04
This fixed it for me in Swift 3:  Add this to your UIViewController

    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        if var topController = UIApplication.shared.keyWindow?.rootViewController {
            while let presentedViewController = topController.presentedViewController {
                topController = presentedViewController
            }
            topController.view.frame.origin = CGPoint(x: 0, y: 0)
        }
    }

**Comment by hackiftekhar** [comment] 2018-03-14 14:12
It's fixed with new solution, changes are in master branch now. Please check and let me know if it doesn't work for you.

**Closed by hackiftekhar** 2018-03-14 14:12 UTC
Labels: bug
