### ISSUE TITLE
Next arrow bug Swift

### ISSUE THREAD

**Issue by maurovc** [hackiftekhar/IQKeyboardManager#476] opened 2016-04-03 14:27 UTC
Hi there I've found a bug in the next arrow action selector.

In IQUIView+IQKeyboardToolbar when the selector is assigned to the button there's an error in two of those case (lines 955 and 829) where the action assigned is previousAction and not nextAction.

Best regards,

Mauro

**Comment by hackiftekhar** [comment] 2016-04-03 18:08
Possibly duplicate of #459. Could you please confirm?

**Comment by maurovc** [comment] 2016-04-03 18:15
It looks like yes!

**Closed** 2016-04-04 03:10 UTC
Labels: duplicate
