### ISSUE TITLE
iOS 16.1 has no done button's view displayed above the keyboard in SwiftUI

### ISSUE THREAD

**Issue by kuzomenskyi** [hackiftekhar/IQKeyboardManager#1924] opened 2022-11-05 19:55 UTC
**Describe the bug**
SwiftUI application does not display Done view above the keyboard while running on iOS 16.1. This could be seen on this screenshot https://prnt.sc/WrR_kXjqLtjn

**To Reproduce**
1. Pull this repo;
2. Run on simulator;
3. Tap on "Text" textfield to see the keyboard.

**Expected behavior**
Done view displayed above the keyboard like so https://prnt.sc/xv5KWL-Mpx7n

**Screenshots**
https://prnt.sc/Jd3VqJrDhgeG

**Demo Project**
https://github.com/kuzomenskyi/IQKeyboardManager-iOS-16.1-no-done-view

### Versions
**Xcode:** 14.1 (14B47b)
**Mac OS:** 12.6
**Simulator/Device:** 16.1
**Simulator/Device Name:** iPhone 11
**Library Version:** x.x.x

**Additional context**
Does not work neither on device nor on simulator

**Comment by rootkishorsoneji** [comment] 2022-11-08 12:33
@kuzomenskyi  do you get any solution? because I am facing the same issue.

**Comment by kuzomenskyi** [comment] 2022-11-08 12:37
> @kuzomenskyi do you get any solution? because I am facing the same issue.

I thought someone has a workaround for this issue but it is been 3 days now and nobody has it so I will wait or fix it myself and create a pull-request.

Anyway, I will keep this post updated

**Comment by abinhho** [comment] 2022-11-25 04:27
Same here. iOS 16.1

**Comment by Kamaljeetsinghpunia** [comment] 2023-01-15 09:01
Same issue in iOS 16.2

**Comment by fuggly** [comment] 2023-01-18 14:19
@kuzomenskyi  Out of curiosity: why did you close this? On iOS 16.2 SwiftUI TextViews still don't have a toolbar. Do you have a working solution for this?

**Comment by fuggly** [comment] 2023-01-19 07:32
@kuzomenskyi  I would appreciate if you could reopen the issue since it isn't really solved. I tried debugging it yesterday but I have a feeling that the problem is SwiftUI 3. It adds an inputAccessoryView to each TextView, but it is invisible (has a 0 size). That confuses IQKeyboardManager because it thinks it already has a toolbar.
However.. even when I drop that check inside IQKeyboardManager and verify that it assigns its toolbar to the inputAccessoryView of that TextView, it still doesn't show, but I didn't have more time to dwell into that yet. Also it only happens with TextViews, not with TextFields (UITextField works, UITextView doesn't), whyever...

**Closed** 2023-06-13 17:44 UTC
