### ISSUE TITLE
Constraints aligned to SafeArea Top mispositioned in iOS 11 with textfield/textview

### ISSUE THREAD

**Issue by Kidreams** [hackiftekhar/IQKeyboardManager#1266] opened 2018-03-09 04:39 UTC
I have a textfield / textview in UIViewController.view and any element that aligned to SafeArea Top (status bar) will glitch after keyboard show and hide due safeAreaInsets top and bottom inset changed to zero.
Condition: Using NavigationViewController as Initial ViewController and set NavigationBar to hidden.

### Steps to Reproduce

1. Create a project and initial ViewController using NavigationViewController
2. add a label/button align to safe area top (with constant = 0, easier to observe).
3. add textfield to near the bottom of the view
4. make textfield becomeFirstResponder and resign it.

The view would move up due to keyboard present and move back to pervious position after keyboard dismiss.

But all elements aligned to SafeArea with NavigationBar hidden will glitch and aligned to superview top.

This is quite easy to reproduce.

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.1.2, 11.2, 11.2.5

**Simulator/Device Name:** iPhone X, iPhone 6s

**Library Version:** 5.0.7

Video link : https://www.dropbox.com/s/37xgbx28rq0ha9g/IMG_0071.TRIM.MOV?dl=0

**Comment by hackiftekhar** [comment] 2018-03-12 06:21
I'm working on another approach to fix this issue, let's see if that works with us.

**Comment by hackiftekhar** [comment] 2018-03-14 13:38
It's fixed with new solution, changes are in `master` branch now.

**Closed by hackiftekhar** 2018-03-14 13:38 UTC

**Comment by svyatoslav-reshetnikov** [comment] 2019-02-26 10:20
Hello,

I want to report you that this problem is reproducing again. I'm using [PinLayout](https://github.com/layoutBox/PinLayout) for make a layout. Fist time it seems ok, I set a cursor into textfield and write some message. But if I try to unset a cursor from textfield and set it second time - I can see this bug. However, if I try to unset cursor again and set it third time - I see that layout is right again.

**Comment by hackiftekhar** [comment] 2019-03-26 16:38
Hmm, can you be sure it happens when you use PinLayout library?

**Comment by hackiftekhar** [comment] 2019-03-26 16:38
Are you sure the layout library isn't doing anything in the middle?

**Comment by svyatoslav-reshetnikov** [comment] 2019-03-26 16:56
> Hmm, can you be sure it happens when you use PinLayout library?

It also happens without PinLayout. I checked it.

**Comment by hackiftekhar** [comment] 2019-03-26 16:57
Ok, can you please send me the demo project here?

**Comment by svyatoslav-reshetnikov** [comment] 2019-03-26 17:00
> Ok, can you please send me the demo project here?

It takes time. I will send it to you in the end of this week because I have a lot of job.

**Comment by headsUpVir** [comment] 2020-01-09 11:18
I am facing the same issue, iOS 11 to 13, Xcode 11

There is UITableView on top and UITextView on bottom, constrained to SafeArea

After modifying textView or closing the keyboard, the constraints update to Superview
