### ISSUE TITLE
Does not work perfectly with UITextView while using enabledDistanceHandlingClasses

### ISSUE THREAD

**Issue by zzyspace** [hackiftekhar/IQKeyboardManager#772] opened 2017-02-16 06:40 UTC
If IQKeyboardManager working automatically, It's everything fine. But It has some problem when I disabled managing distance, and add the controller class to enabledDistanceHandlingClasses, there just first touch UITextView can handle distance, after that distance handling don't work.
By the way, distance handling with UITextField is working fine.

This is my [Demo](https://www.dropbox.com/s/begaubed94qna44/testtest.zip?dl=0):
if do nothing on AppDelegate, it works fine.
else if using following code, the bug occur.

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Following code cause the bug
    [IQKeyboardManager sharedManager].enable = NO;
    [[[IQKeyboardManager sharedManager] enabledDistanceHandlingClasses] addObject:[ViewController class]];
    return YES;
}
```

**Comment by hackiftekhar** [comment] 2017-02-22 03:28
Thanks for the report and demo project, I'll try your demo when I get some time.

**Comment by malkabani** [comment] 2017-02-23 12:37
Hi. Is there any solution for this bug. thanks

**Comment by zzyspace** [comment] 2017-02-24 04:54
@malkabani Hi, there is my temporary solution, but it is not the ultimate solution:

```objc
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    [IQKeyboardManager sharedManager].enable = YES;
}

- (void)viewDidDisappear:(BOOL)animated
{
    [super viewDidDisappear:animated];
    [IQKeyboardManager sharedManager].enable = NO;
}
```

**Comment by lingzlu** [comment] 2017-03-01 19:17
I'm having similar issue, seems to be the issue with UITextView `didBeginEditing` gets call after keyboard event . just opened issue #784, which would be duplicate of this one

**Comment by hackiftekhar** [comment] 2017-04-01 17:40
Hey @zzyspace I checked the demo and this looks to be an issue, however I didn't check at code level so I need some time for detailed investigation.

**Closed** 2017-04-04 06:41 UTC
Labels: Need Investgation

**Comment by zzyspace** [comment] 2017-04-04 06:45
@hackiftekhar Great!

**Comment by hackiftekhar** [comment] 2017-04-04 06:47
Cheers @zzyspace
