### ISSUE TITLE
setCustomDoneTarget method not Found

### ISSUE THREAD

**Issue by MahipalV12** [hackiftekhar/IQKeyboardManager#1133] opened 2017-11-15 10:53 UTC
setCustomDoneTarget is showing error and not found in recent update (available till 4.0.8). Is there any other option or method to set Custom Done target on textfield

**Comment by hackiftekhar** [comment] 2017-11-23 06:51
It's replaced by another mechanism. Duplicate of https://github.com/hackiftekhar/IQKeyboardManager/issues/1016 https://github.com/hackiftekhar/IQKeyboardManager/issues/979

**Closed** 2018-01-03 12:58 UTC
