### ISSUE TITLE
How full screen uitextview.and display UINavigationBar

### ISSUE THREAD

**Issue by controlrole** [hackiftekhar/IQKeyboardManager#219] opened 2015-05-21 12:03 UTC
how are you
my not using storyboard or xib,and override
-(void)loadView
    {
        UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
        self.view = scrollView;
    }
- (void)viewDidLoad 
{
    [self.view addSubview:mytextview];
}
UINavigationBar disappeared  my not want it disappeared.how do?
thanks

**Comment by hackiftekhar** [comment] 2015-05-31 17:22
Not able to reproduce it with your suggested conditions/code, please send me demo.

**Comment by hackiftekhar** [comment] 2015-06-22 05:45
Any updates or any demo code for me to debug?

**Comment by hackiftekhar** [comment] 2015-07-08 05:49
Closing because didn't get any updates on the above issue.

**Comment by controlrole** [comment] 2015-07-08 05:55
my send your email

**Comment by hackiftekhar** [comment] 2015-07-08 09:06
Thanks for the reminder. I'll check it today.

**Comment by hackiftekhar** [comment] 2015-07-08 11:37
I checked the demo app, but it may take some time to fix it.

**Comment by hackiftekhar** [comment] 2015-08-27 12:26
I think this issue is addressed here 6b6cd58b5cbb8efb66c3b69506c672cd9a01b21d (Assuming textView.frame.y is not less than zero), now when UITextView will be inside of UIScrollView then scrollView will take care of all the things and will not affect UINavigationBar or UiTextView height.

**Closed by hackiftekhar** 2015-08-27 12:26 UTC
Labels: bug
