### ISSUE TITLE
Scroll not returning to origin, leaving more & more blank space at top

### ISSUE THREAD

**Issue by REAOrlando** [hackiftekhar/IQKeyboardManager#1055] opened 2017-10-10 04:39 UTC
![giphy](https://user-images.githubusercontent.com/24299944/31369414-468a56fe-ad52-11e7-9aac-b12cfadee176.gif)

I'm not sure if this is Xcode9 or iOS 11 but I just noticed that on this app when the view scrolls up with the keyboard appearing, it isn't returning to the original position after the keyboard is dismissed.  It actually is moved down slightly each time.  You'll see in the gif above, the space at top keeps expanding.  This view doesn't have any other scrollviews, just IQKeyboardManager through cocoa pods with latest version as 'IQKeyboardManagerSwift', ‘4.0.12’.

**Comment by vidurgupta01** [comment] 2017-10-10 08:48
I am also having the same issue.

**Comment by marcospolanco** [comment] 2017-10-11 16:11
Same. Using pod 'IQKeyboardManagerSwift', '5.0.0'. In my case the UITextView is embedded within a UITabBarController, and the gap above is cascading over to the other view controllers in the tab bar as well. Using Swift 3 on XCode 9.

**Comment by aravasio** [comment] 2017-10-11 23:11
Me too. I'm trying to figure out what it might be, to no success. I'm not able to reproduce on iOS10, btw.

**Comment by kylexy32** [comment] 2017-10-12 00:43
Yes, I have had no problems on iOS 11 and even when I download my app which
was complied using IQKeyboardManager 4.0.2 has no problems on iOS 11. But
using the latest IQKeyboardManager 5.0.3, I cannot get around this issue.
Any ideas??

**Comment by REAOrlando** [comment] 2017-10-12 05:46
I can't confirm this but it seems that the issue _may_ begin only when the navigation bar is scrolled out of view.  When navBar returns to it's original position there is extra padding added below it. Every time the navBar scrolls up out of view and returns the added padding repeats so the white space continues to grow.

**Comment by Lovyom** [comment] 2017-10-12 12:45
I too facing this issue in my app which is being running from long back, Please suggest or fix the issue as soon as you can.

As at this stage of project we can't change our code for keyboard handling.

**Comment by hackiftekhar** [comment] 2017-10-12 18:29
Can someone upload sample code so we can debug the issue?

**Comment by marcospolanco** [comment] 2017-10-12 18:52
@hackiftekhar Here's a sample project. Thx!

[SpacyText.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1380338/SpacyText.zip)

**Comment by marcospolanco** [comment] 2017-10-12 19:09
My testing shows that the problem is proportional to the magnitude of the layout constraint between the TextView and the Top Layout Guide. 'Alight Top to: Safe Area' of 0-5 eliminates the issue. Use '6' and the effect starts but it is small without lots of repetitions. Larger numbers make it more obvious.  I've attached an updated version that eliminates an extraneous view in the earlier one.
[SpacyText.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1380379/SpacyText.zip)

**Comment by hackiftekhar** [comment] 2017-10-12 19:30
I'm not able to reproduce the gap issue. Can you please let me know with which configuration you are able to reproduce this issue @marcospolanco ?

**Comment by marcospolanco** [comment] 2017-10-12 19:52
@hackiftekhar Running iPhone 7, iOS 11.0.1

**Comment by aravasio** [comment] 2017-10-12 20:00
[SpacyText.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1380510/SpacyText.zip)

@hackiftekhar this is literally the same project @marcospolanco created, but I changed the textField's top constraint to safe area from 6 to 40, since at 6 progression is incredibly subtle and might pass as a non-issue. At 40 its glaringly obvious at 2 o 3 iterations.

**Comment by jahid-hasan-polash** [comment] 2017-10-16 10:19
I am having the same issue. Using 4.0.13 and swift 3. the fix @marcospolanco gave didn't work for me.

**Comment by AmrKafina** [comment] 2017-10-17 03:18
I'm having this issue when manually hiding the view controller's navigation bar. The 'gap' increase depends on the top layout constraint, as pointed out by @marcospolanco. 

Keeping the navigation bar visible doesn't seem to trigger the issue.

**Comment by AdnanAsghar** [comment] 2017-10-20 12:08
<img width="257" alt="screen shot 2017-10-20 at 5 06 35 pm" src="https://user-images.githubusercontent.com/23141110/31820102-1d7da92c-b5b9-11e7-9086-1a691b4465e7.png">

Removing the constraint from top layout guide and adding to superview worked for me

**Comment by HungoHung** [comment] 2017-10-24 09:31
@AdnanAsghar 's solution fix the issue on my case. Thanks a lot. ^^

**Comment by egonza26** [comment] 2017-10-24 14:57
@AdnanAsghar thanks a lot man!!

**Comment by REAOrlando** [comment] 2017-10-24 15:27
Anyone know how to keep the navigation bar at the top as AmrKafina has suggested. I've seen other posts suggesting this was discussed in the README file but it looks like it has been removed.

**Comment by H03in** [comment] 2017-10-26 03:01
@AdnanAsghar tanks man! solved my problem too.

**Comment by MihaiEBS** [comment] 2017-10-31 14:24
try to use IQKeyboardManager (Objective-C version)
pod 'IQKeyboardManager'

**Comment by VladCojanu** [comment] 2017-11-01 02:44
I'm having this issue using 5.0.4 with Swift 4 on iOS 11, none of the posted solutions worked for me :( 
My issue is occurring on a screen with a navigation controller.

**Comment by dadazombie** [comment] 2017-11-06 01:15
@AdnanAsghar solution fix my problem, thanks a lot! By the way, my text view is align to the top of safe area instead of top layout guide.

**Comment by REAOrlando** [comment] 2017-11-12 02:35
@MihaiEBS I tried the Obj-C version as well and different issue, status bar turning all black when the navigation bar returned to its original place.  For now, I removed the status bar by forcing the app into full screen and that solved the issue for now.

**Comment by DilipMobi** [comment] 2017-11-18 06:40
@hackiftekhar i had found bug 
here you can check all things
https://drive.google.com/open?id=1LVay1YXrRjzhrDO24VHkRxnnkwb53sw0

**Comment by hackiftekhar** [comment] 2017-11-20 05:18
I tried this demo with Xcode9.1 and I'm unable to reproduce this issue with iOS11.1. @DilipMobi could you please let me know what should I do now?

**Comment by DilipMobi** [comment] 2017-11-21 03:34
@hackiftekhar  see also my video(issueVideo.mov) i attached with this link.
it continue reproduce space bug on top after every third step. i had also attached text file(reproduce bug.rtf) also in which step it will adding extra white space on top and next step it will correct the screen spacing.It only happen when you using TabBar controller.

**Comment by hackiftekhar** [comment] 2017-11-21 04:10
I already saw your video and steps you mentioned. But it wasn't reproducible. Could you please let me know which Xcode version you are able to reproduce with which simulator?

**Comment by VladCojanu** [comment] 2017-11-21 05:03
I fixed my issue by setting @property BOOL canAdjustAdditionalSafeAreaInsets to true.

**Comment by hackiftekhar** [comment] 2017-11-21 09:42
But still I need answer of my question.

**Comment by DilipMobi** [comment] 2017-11-22 12:44
@hackiftekhar 
X-Code Version 9.1 (9B55)
iPhone 6
iOS 11.0.3
1)In my video push  at 0:10 show Top Label size (it is original)
2)on  0:14 it will become tiny
3)on 0:16 sec it will leave extra space on top label and size of label reduce 
4)on 0:25 it will become original size
5)On 1:27 whole black label showing down side then it was actual at 0 from top
when ever use TabBarcontroller it will add extra space on top

**Comment by hackiftekhar** [comment] 2018-03-14 13:47
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Closed by hackiftekhar** 2018-03-14 13:47 UTC
