### ISSUE TITLE
Keyboard stops working after Actionsheet appear for save password

### ISSUE THREAD

**Issue by sarojraut** [hackiftekhar/IQKeyboardManager#1958] opened 2023-05-03 01:02 UTC
After successfull signup, app shows actionsheet to save password and on cancel IQKeyboard manager stops working

**To Reproduce**
1. Make textfield contenttype as password
2. click cancel on save password actionsheet

### Versions
Xcode: 14.2
Mac OS: 13.2.1
ios 16.4.1
 iPhone 13 pro max
Library Version: 6.5.11

**Comment by OrochiChris** [comment] 2023-07-27 09:19
I also encountered the same problem. This operation will cause the entire IQKeyboardManager to fail. Even if it is re-enabled with code, it will not work. You can only restart the app, which will have a great impact. Currently considering replacing other libraries

**Comment by hackiftekhar** [comment] 2023-09-28 14:50
Can you please share a demo project with me?

**Comment by hackiftekhar** [comment] 2023-11-02 14:22
It looks like a duplicate of #1763

**Closed by hackiftekhar** 2023-11-02 14:22 UTC
Labels: Demo Requested
