### ISSUE TITLE
Swift 3 branch issues

### ISSUE THREAD

**Issue by slynglen** [hackiftekhar/IQKeyboardManager#563] opened 2016-07-13 11:23 UTC
Hello

I got a few issues when using the Swift 3 branch.

- Line 690 in IQKeyboardManager.swift seems to be a duplicated line of 687.
- Ambiguous use of '`textView(_:shouldInteractWith:in:interaction)`' on lines 448, 458, 468 and 478 in IQKeyboardReturnKeyHandler.swift

Can you fix that? :-)

Nice project!

**Comment by hackiftekhar** [comment] 2016-07-13 11:32
Could you please make a pull-request. Unfortunately I don't have Xcode 8 Beta so I don't exactly know where the issue is, the swift3 branch was updated yesterday by a pull reqeust.

**Comment by ltsuda** [comment] 2016-07-13 19:51
Hi @slynglen, I did the Swift 3 PR and commented that in those lines I've this "Ambiguous use" issue too.

If you option+click in these function, you'll see that both have the same function signature and when we use as a Selector, we receive the "Ambiguous use" issue. I couldn't find a solution.

**Comment by Tulleb** [comment] 2016-07-27 11:10
I can't find the PR where you propose the fixes @ltsuda, could you link it here please?
I found [this one](https://github.com/hackiftekhar/IQKeyboardManager/pull/558) but it seems it was merged without @slynglen shown issues.

**Comment by ltsuda** [comment] 2016-07-27 19:26
This PR you found was merged and I have mention that was errors and warnings, the same as @slynglen commented in this issue.

I couldn't fix those errors, I hope someone with more knowledge could help.

- There're error in these files below:
IQKeyboardManager.swift
IQKeyboardReturnKeyHandler.swift

**Comment by tiferrei** [comment] 2016-07-28 20:41
@ltsuda & @hackiftekhar: The problem on `IQKeyboardManager.swift` I believe is just a duplicate of a variable declaration as [line 960](https://github.com/hackiftekhar/IQKeyboardManager/blob/swift3/IQKeyboardManagerSwift/IQKeyboardManager.swift#L690) is repeated.

On `IQKeyboardReturnKeyHandler.swift` it seems to be because there are 2 functions, who take different parameters, but have the same name, causing a conflict when calling them as a `#selector`. I am not sure how to solve that one though.

**Comment by ltsuda** [comment] 2016-07-29 18:16
Hi @tiferrei, this is the exactly problem. I found some reports about Swift 3 in these kind of problem but I couldn't solve here.

**Comment by Tulleb** [comment] 2016-08-01 12:04
PR waiting for approval @hackiftekhar.

**Comment by parasdaff** [comment] 2016-08-03 07:17
@hackiftekhar Can you please update the branch with pull request from @Tulleb .

**Comment by Tulleb** [comment] 2016-08-03 08:17
Meanwhile you can pod my own branch if you are in a hurry @parasdaff:
`pod 'IQKeyboardManagerSwift', :git => 'https://github.com/Tulleb/IQKeyboardManager.git', :branch => 'swift3'`

**Comment by hackiftekhar** [comment] 2016-08-06 19:04
Merged!

**Comment by Tulleb** [comment] 2016-08-16 11:10
Duplicate of #531.

**Closed** 2016-08-16 18:03 UTC
