### ISSUE TITLE
Installation with Swift Package Manager does not provide functionality

### ISSUE THREAD

**Issue by VitaliyKurbatov** [hackiftekhar/IQKeyboardManager#1765] opened 2020-10-29 15:00 UTC
**Describe the bug**
Functionality not worked.

**To Reproduce**
Installed IQKeyboardManager package via Xcode with steps:
* Go to File -> Swift Packages -> Add Package Dependency...
 * Then search for https://github.com/hackiftekhar/IQKeyboardManager.git
 * And choose the version you want
Dependency successfully implemented.

**Expected behavior**
Functionality works great

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-10-29 at 17 53 44](https://user-images.githubusercontent.com/37406867/97590546-c95bcb80-1a0f-11eb-9544-67118afdee05.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-29 at 17 53 53](https://user-images.githubusercontent.com/37406867/97590563-ccef5280-1a0f-11eb-98ce-a36868709080.png)

**Demo Project**
[SPMProject.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/5459190/SPMProject.zip)

### Versions
**Xcode:** 12.1
**Mac OS:** Catalina 10.15.7
**Simulator/Device:** 14.1
**Simulator/Device Name:** iPhone 11
**Library Version:** 6.5.6

**Comment by Kedar-27** [comment] 2020-10-29 22:06
> **Describe the bug**
> Functionality not worked.
> 
> **To Reproduce**
> Installed IQKeyboardManager package via Xcode with steps:
> 
> * Go to File -> Swift Packages -> Add Package Dependency...
> * Then search for https://github.com/hackiftekhar/IQKeyboardManager.git
> * And choose the version you want
>   Dependency successfully implemented.
> 
> **Expected behavior**
> Functionality works great
> 
> **Screenshots**
> ![Simulator Screen Shot - iPhone 11 - 2020-10-29 at 17 53 44](https://user-images.githubusercontent.com/37406867/97590546-c95bcb80-1a0f-11eb-9544-67118afdee05.png)
> ![Simulator Screen Shot - iPhone 11 - 2020-10-29 at 17 53 53](https://user-images.githubusercontent.com/37406867/97590563-ccef5280-1a0f-11eb-98ce-a36868709080.png)
> 
> **Demo Project**
> [SPMProject.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/5459190/SPMProject.zip)
> 
> ### Versions
> **Xcode:** 12.1
> **Mac OS:** Catalina 10.15.7
> **Simulator/Device:** 14.1
> **Simulator/Device Name:** iPhone 11
> **Library Version:** 6.5.6

Its not working due to iOS 14

**Comment by Kedar-27** [comment] 2020-10-29 22:08
its not working due to iOS 14
Duplicate of #1758

**Closed** 2021-11-06 14:59 UTC
