### ISSUE TITLE
compile failed with method conflict error 

### ISSUE THREAD

**Issue by LeeKM** [hackiftekhar/IQKeyboardManager#595] opened 2016-08-04 12:00 UTC
when i has code below in my project

```
class CustomView: UIView {
     weak var viewController : ViewController?
}
```

I got an compile error
`Getter for 'viewController' with Objective-C selector 'viewController' conflicts with method 'viewController()' from superclass 'UIView' with the same Objective-C selector`,is there any way to fix this problem without changing my code ?

**Comment by hackiftekhar** [comment] 2016-08-06 18:54
You are getting this because there is a ViewController method in a UIView category in my lubrary. You could try changing your variable name.

**Comment by hackiftekhar** [comment] 2016-10-20 18:10
I checked this and found that if UIView has other category class having same method name then library code compiles fine and works fine. This is the only issue with subclasses. So I decided to keep `viewController` method name as it is and doesn't change anything.

**Comment by dodikk** [comment] 2018-03-13 12:01
@hackiftekhar , I am experiencing a similar issue. My project is using both `IQKeyboardManager` and a proprietary [Scandit SDK](https://www.scandit.com/products/barcode-scanner/)

The name conflict is caused by two third-parties, so changing a property name is not an option for me.
What would you suggest?


```obj-c
@interface SBSBarcodePickerView : UIView
{
  // ...

   @property (nonnull, nonatomic, strong, readonly) SBSBarcodePicker *viewController;
}
```


P.S. Could you please re-consider using some sort of prefixes for your UIKit extensions?

**Comment by dodikk** [comment] 2018-03-13 12:03
Detaching the introspection logic from UIView could be a good option too.
That would look a bit less "elegant" but a class would implicitly get the swift module's namespace and hence it would be protected from such naming conflicts.

```swift
class UIViewUtils
{
   public static func viewController(for view: UIView)->UIViewController? 
   {
        var nextResponder: UIResponder? = view
        
        repeat {
            nextResponder = nextResponder?.next
            
            if let viewController = nextResponder as? UIViewController {
                return viewController
            }
            
        } while nextResponder != nil
        
        return nil
   }


// rest of IQUIView+Hierarchy methods rewritten in the same manner
}
```

**Comment by dodikk** [comment] 2018-03-13 12:29
So my workaround is making another category... In Objective-C...


```obj-c
#import <ScanditBarcodeScanner/ScanditBarcodeScanner.h>

@interface SBSBarcodePickerView (ViewControllerGetter)

@property (nonnull, nonatomic, strong, readonly) SBSBarcodePicker* scanVC;

@end
```

```obj-c
#import "SBSBarcodePickerView+ViewControllerGetter.h"

@implementation SBSBarcodePickerView (ViewControllerGetter)

@dynamic scanVC;

-(SBSBarcodePicker*)scanVC
{
    // have to redefine the property
    // due to IQKeyboardManager name conflict
    //
    // https://github.com/hackiftekhar/IQKeyboardManager/issues/595
    //
    
    return self.viewController;
}

@end
```

**Comment by hackiftekhar** [comment] 2018-03-15 12:14
It's now fixed

**Closed by hackiftekhar** 2018-03-15 12:14 UTC
Labels: enhancement
