### ISSUE TITLE
set the extension property of textView to disable will cause the keyboard display of other objects to be abnormal

### ISSUE THREAD

**Issue by leidi0129** [hackiftekhar/IQKeyboardManager#2000] opened 2023-11-24 04:17 UTC
**Describe the bug**
If I set any "textView.enableMode = IQEnableModeDisabled", it will cause the keyboards of other input boxes to not pop up.
I guess it's due to differences in the timing of _kbFrame variable settings. In the keyboardWillShowNoti method, _kbFrame is updated before [self privateIsEnabled], but not update _kbFrame in the keyboardWillHideNoti method,.

**To Reproduce**
1. set textView1.enableMode = IQEnableModeDisabled, textView2.enableMode = IQEnableModeEnable
2. Click on 'textView1'
3. Them click on 'textView2'

**Expected behavior**
The keyboard should show when I click on 'textView2'

**Screenshots**
![image](https://github.com/hackiftekhar/IQKeyboardManager/assets/11567481/1737a76a-a90f-4084-bf0e-1f6d596f1f9b)
![image](https://github.com/hackiftekhar/IQKeyboardManager/assets/11567481/a1267c2c-f838-4541-8298-ed2455ceba42)

**Comment by hackiftekhar** [comment] 2023-11-25 14:51
Thanks for these details, I'll take a look

**Comment by hackiftekhar** [comment] 2023-11-27 08:27
@leidi0129 Can you please share a video how it's behaving. I'm unable to reproduce the abnormal behavior.

**Comment by leidi0129** [comment] 2023-11-27 09:03
![demo](https://github.com/hackiftekhar/IQKeyboardManager/assets/11567481/1ad440ae-2526-4f05-a797-145c755d7e46)

https://github.com/hackiftekhar/IQKeyboardManager/assets/11567481/1e03c23b-2c26-4a78-9aec-97f8c84aabd1

**Comment by hackiftekhar** [comment] 2023-11-27 10:53
Thanks for this demo. I'll investigate now.

**Comment by hackiftekhar** [comment] 2024-01-09 15:21
This issue looks to be fixed in main branch.

**Closed by hackiftekhar** 2024-01-09 15:21 UTC
