### ISSUE TITLE
How to stop extra scrolling when keyboard is visible.

### ISSUE THREAD

**Issue by sinhagaurav010** [hackiftekhar/IQKeyboardManager#487] opened 2016-04-13 11:25 UTC
Thanks for your great work..!!
When keyboard is visible, screen is scrollable with a high contentSize.
Is there any way to stop this extra scrolling? I only want screen to scroll till the UITextField set just above keyboard.

**Comment by abellee** [comment] 2016-05-01 03:04
I have the same problem on iOS 7.

**Comment by hackiftekhar** [comment] 2016-05-15 07:19
Looks like a duplicate of #485. Could you please confirm?

**Closed** 2016-05-16 07:48 UTC
Labels: Needs Feedback
