### ISSUE TITLE
 Keyboard gets stuck in ios 13 simulator！

### ISSUE THREAD

**Issue by Goallying** [hackiftekhar/IQKeyboardManager#1600] opened 2019-09-23 03:45 UTC
Keyboard gets stuck in ios 13 simulator ，i cant edit my textfileds. what happend?

**Comment by hackiftekhar** [comment] 2019-09-23 05:42
Please debug your application to find out the line of code where the keyboard stucks.

**Comment by g623171541** [comment] 2019-09-23 06:15
Textfield secure entry on my iOS 13 has this problem. [screenshot](https://note.youdao.com/yws/public/resource/0c5960d39e17b78b6acca0f40be47e12/xmlnote/WEBRESOURCE14e3b3ebf7abb9e4694b47bc0a3cb5e2/8300)

**Comment by MagicXiaoXiao** [comment] 2019-09-23 06:28
Me too!

**Comment by nodediggity** [comment] 2019-09-23 07:19
I'm seeing the same behaviour.

Seem to have a bunch of constraint issues also:

```
Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
    (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600001ed8780 h=--& v=--& _UIToolbarContentView:0x7fcdad54ac40.width == 0   (active)>",
    "<NSLayoutConstraint:0x600001ef0280 H:|-(0)-[_UIButtonBarStackView:0x7fcdad60af80]   (active, names: '|':_UIToolbarContentView:0x7fcdad54ac40 )>",
    "<NSLayoutConstraint:0x600001ef1270 _UIButtonBarStackView:0x7fcdad60af80.trailing == _UIToolbarContentView:0x7fcdad54ac40.trailing   (active)>",
    "<NSLayoutConstraint:0x600001ef3d40 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x7fcdad625bd0'Done']   (active, names: '|':_UIButtonBarButton:0x7fcdad625680 )>",
    "<NSLayoutConstraint:0x600001ef3f20 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fcdad625bd0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7fcdad625680 )>",
    "<NSLayoutConstraint:0x600001ef0050 'UISV-canvas-connection' UILayoutGuide:0x6000004a50a0'UIViewLayoutMarginsGuide'.leading == UIView:0x7fcdad6253c0.leading   (active)>",
    "<NSLayoutConstraint:0x600001ef0000 'UISV-canvas-connection' UILayoutGuide:0x6000004a50a0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7fcdad625680.trailing   (active)>",
    "<NSLayoutConstraint:0x600001eafc00 'UISV-spacing' H:[UIView:0x7fcdad6253c0]-(0)-[UIView:0x7fcdb0706920]   (active)>",
    "<NSLayoutConstraint:0x600001ed8000 'UISV-spacing' H:[UIView:0x7fcdb0706920]-(0)-[UIView:0x7fcdad625520]   (active)>",
    "<NSLayoutConstraint:0x600001ed8050 'UISV-spacing' H:[UIView:0x7fcdad625520]-(0)-[_UIButtonBarButton:0x7fcdad625680]   (active)>",
    "<NSLayoutConstraint:0x600001eb3f20 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x6000004a50a0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7fcdad60af80 )>",
    "<NSLayoutConstraint:0x600001eb5270 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x6000004a50a0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7fcdad60af80 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600001ef3f20 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fcdad625bd0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7fcdad625680 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

**Comment by BruceLilonglong** [comment] 2019-09-23 08:38
When using the keyboard code crash with TextField.becomeFirstResponder() and [UIButton setTintColor]!

**Comment by hackiftekhar** [comment] 2019-09-23 11:07
Can you please send screenshot of the crash?

**Comment by NasrullahKhan** [comment] 2019-09-23 11:30
facing same issue on xcode 11 iOS 13. Kindly figure it out.

**Comment by surjava5635xxx** [comment] 2019-09-23 12:35
My picker View gets stuck and nothing works after that. Same constraints breaking... 
[https://i.ibb.co/MsPsK8K/Screen-Shot-2019-09-23-at-6-02-49-PM.png](url)
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600000ace940 h=--& v=--& _UIToolbarContentView:0x7f9e8aef8920.width == 0   (active)>",
    "<NSLayoutConstraint:0x600000ab8780 H:|-(0)-[_UIButtonBarStackView:0x7f9e8aef8c80]   (active, names: '|':_UIToolbarContentView:0x7f9e8aef8920 )>",
    "<NSLayoutConstraint:0x600000ab87d0 _UIButtonBarStackView:0x7f9e8aef8c80.trailing == _UIToolbarContentView:0x7f9e8aef8920.trailing   (active)>",
    "<NSLayoutConstraint:0x600000acdb30 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x7f9e8d7379c0'Done']   (active, names: '|':_UIButtonBarButton:0x7f9e8d736e00 )>",
    "<NSLayoutConstraint:0x600000acdb80 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7f9e8d7379c0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7f9e8d736e00 )>",
    "<NSLayoutConstraint:0x600000acdf90 'UISV-canvas-connection' UILayoutGuide:0x60000109bd40'UIViewLayoutMarginsGuide'.leading == UIView:0x7f9e8d736b40.leading   (active)>",
    "<NSLayoutConstraint:0x600000acdfe0 'UISV-canvas-connection' UILayoutGuide:0x60000109bd40'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7f9e8d736e00.trailing   (active)>",
    "<NSLayoutConstraint:0x600000ace170 'UISV-spacing' H:[UIView:0x7f9e8d736b40]-(0)-[UIView:0x7f9e8aef7c90]   (active)>",
    "<NSLayoutConstraint:0x600000ace1c0 'UISV-spacing' H:[UIView:0x7f9e8aef7c90]-(0)-[UIView:0x7f9e8d736ca0]   (active)>",
    "<NSLayoutConstraint:0x600000ace210 'UISV-spacing' H:[UIView:0x7f9e8d736ca0]-(0)-[_UIButtonBarButton:0x7f9e8d736e00]   (active)>",
    "<NSLayoutConstraint:0x600000ab85f0 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x60000109bd40'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7f9e8aef8c80 )>",
    "<NSLayoutConstraint:0x600000ab8690 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x60000109bd40'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7f9e8aef8c80 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000acdb80 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7f9e8d7379c0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7f9e8d736e00 )>

**Comment by duke4e** [comment] 2019-09-23 13:17
Looks like this is a simulator bug.

I'm just trying out this fix:
> As a workaround, you can disable 'Automatically Sync Pasteboard'.
> Simulator -> Edit -> Automatically Sync Pasteboard

**Comment by milika** [comment] 2019-09-24 00:36
+1 same issue - workaround not doing anything...

**Comment by milika** [comment] 2019-09-24 00:38
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600003cfae90 h=--& v=--& _UIToolbarContentView:0x7fd91dd17dc0.width == 0   (active)>",
    "<NSLayoutConstraint:0x600003cd0050 H:|-(0)-[_UIButtonBarStackView:0x7fd91dd227d0]   (active, names: '|':_UIToolbarContentView:0x7fd91dd17dc0 )>",
    "<NSLayoutConstraint:0x600003cd00a0 _UIButtonBarStackView:0x7fd91dd227d0.trailing == _UIToolbarContentView:0x7fd91dd17dc0.trailing   (active)>",
    "<NSLayoutConstraint:0x600003cf9e50 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x7fd91dd4a940'Done']   (active, names: '|':_UIButtonBarButton:0x7fd91dd49400 )>",
    "<NSLayoutConstraint:0x600003cf9ea0 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fd91dd4a940'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7fd91dd49400 )>",
    "<NSLayoutConstraint:0x600003cfa300 'UISV-canvas-connection' UILayoutGuide:0x6000026ec9a0'UIViewLayoutMarginsGuide'.leading == UIView:0x7fd91dd49030.leading   (active)>",
    "<NSLayoutConstraint:0x600003cfa490 'UISV-canvas-connection' UILayoutGuide:0x6000026ec9a0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7fd91dd49400.trailing   (active)>",
    "<NSLayoutConstraint:0x600003cfa4e0 'UISV-spacing' H:[UIView:0x7fd91dd49030]-(0)-[UIView:0x7fd91dd12130]   (active)>",
    "<NSLayoutConstraint:0x600003cfa530 'UISV-spacing' H:[UIView:0x7fd91dd12130]-(0)-[UIView:0x7fd91dd492a0]   (active)>",
    "<NSLayoutConstraint:0x600003cfa580 'UISV-spacing' H:[UIView:0x7fd91dd492a0]-(0)-[_UIButtonBarButton:0x7fd91dd49400]   (active)>",
    "<NSLayoutConstraint:0x600003cdbac0 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x6000026ec9a0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7fd91dd227d0 )>",
    "<NSLayoutConstraint:0x600003cdbe80 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x6000026ec9a0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7fd91dd227d0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003cf9ea0 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fd91dd4a940'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7fd91dd49400 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by LuYu001** [comment] 2019-09-24 01:56
Stuck after using the simulator for a while， reboot simulator can fix ,but still log this:
```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
	<NSAutoresizingMaskLayoutConstraint:0x600003d6ae40 _UIToolbarContentView:0x7f9fa8b2cda0.width == 0>,
	<NSLayoutConstraint:0x600003d2fe80 _UIButtonBarStackView:0x7f9fa8b2d390.leading == _UIToolbarContentView:0x7f9fa8b2cda0.leading>,
	<NSLayoutConstraint:0x600003d2f9d0 _UIButtonBarStackView:0x7f9fa8b2d390.trailing == _UIToolbarContentView:0x7f9fa8b2cda0.trailing>,
	<NSLayoutConstraint:0x600003d6a940 _UIModernBarButton:0x7f9fa648cb20.leading == _UIButtonBarButton:0x7f9fa89620b0.leading + 8>,
	<NSLayoutConstraint:0x600003d68730 _UIButtonBarButton:0x7f9fa89620b0.trailing == _UIModernBarButton:0x7f9fa648cb20.trailing>,
	<NSLayoutConstraint:0x600003d6b250 UILayoutGuide:0x60000273c0e0.leading == UIView:0x7f9fa8963030.leading>,
	<NSLayoutConstraint:0x600003d6b8e0 UILayoutGuide:0x60000273c0e0.trailing == _UIButtonBarButton:0x7f9fa89620b0.trailing>,
	<NSLayoutConstraint:0x600003d69ea0 UIView:0x7f9fa8b2c110.leading == UIView:0x7f9fa8963030.trailing>,
	<NSLayoutConstraint:0x600003d68e60 UIView:0x7f9fa8961f50.leading == UIView:0x7f9fa8b2c110.trailing>,
	<NSLayoutConstraint:0x600003d69310 _UIButtonBarButton:0x7f9fa89620b0.leading == UIView:0x7f9fa8961f50.trailing>,
	<NSLayoutConstraint:0x600003d2f5c0 UILayoutGuide:0x60000273c0e0.left == _UIButtonBarStackView:0x7f9fa8b2d390.left>,
	<NSLayoutConstraint:0x600003d2f020 _UIButtonBarStackView:0x7f9fa8b2d390.right == UILayoutGuide:0x60000273c0e0.right>,
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003d68730 _UIButtonBarButton:0x7f9fa89620b0.trailing == _UIModernBarButton:0x7f9fa648cb20.trailing>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

**Comment by g623171541** [comment] 2019-09-24 02:09
> Looks like this is a simulator bug.
> 
> I'm just trying out this fix:
> 
> > As a workaround, you can disable 'Automatically Sync Pasteboard'.
> > Simulator -> Edit -> Automatically Sync Pasteboard

I tried it on iPhoneXr device, not simulator, the same issus.

**Comment by Pratiksha-torinit** [comment] 2019-09-24 07:32
Same issue with iOS 13 on simulator. Can anybody help me in solving this issue? I just can't access the app anymore. When any textfield is opened, my app freezes.

**Comment by g623171541** [comment] 2019-09-24 10:13
> Textfield secure entry on my iOS 13 has this problem. [screenshot](https://user-gold-cdn.xitu.io/2019/9/23/16d5cc41dec08761?imageView2/0/w/1280/h/960/ignore-error/1)

It's Xcode11 bug, this issue solved with Xcode10.2.

**Comment by sujiewen** [comment] 2019-09-24 14:00
iOS13 simulator Pro or Max Reproduce！

**Comment by jatinj044** [comment] 2019-09-24 17:41
same issue i facing. my iOS 13 simulator not responding after textfield becomeFirstResponde .

`Can't find keyplane that supports type 5 for keyboard iPhone-PortraitChoco-PhonePad; using 25766_PortraitChoco_iPhone-Complex-Pad_Default`

`[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600001846940 h=--& v=--& _UIToolbarContentView:0x7fd40bd35d30.width == 0   (active)>",
    "<NSLayoutConstraint:0x60000182fcf0 H:|-(0)-[_UIButtonBarStackView:0x7fd40bd36200]   (active, names: '|':_UIToolbarContentView:0x7fd40bd35d30 )>",
    "<NSLayoutConstraint:0x60000182fd40 _UIButtonBarStackView:0x7fd40bd36200.trailing == _UIToolbarContentView:0x7fd40bd35d30.trailing   (active)>",
    "<NSLayoutConstraint:0x6000018454f0 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x7fd40bf332a0'Done']   (active, names: '|':_UIButtonBarButton:0x7fd40bf322a0 )>",
    "<NSLayoutConstraint:0x600001845540 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fd40bf332a0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7fd40bf322a0 )>",
    "<NSLayoutConstraint:0x600001845c20 'UISV-canvas-connection' UILayoutGuide:0x6000002642a0'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x7fd40bf2fa40.leading   (active)>",
    "<NSLayoutConstraint:0x600001845c70 'UISV-canvas-connection' UILayoutGuide:0x6000002642a0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7fd40bf322a0.trailing   (active)>",
    "<NSLayoutConstraint:0x600001845cc0 'UISV-spacing' H:[_UIButtonBarButton:0x7fd40bf2fa40]-(0)-[UIView:0x7fd40bf314e0]   (active)>",
    "<NSLayoutConstraint:0x600001845d10 'UISV-spacing' H:[UIView:0x7fd40bf314e0]-(0)-[_UIButtonBarButton:0x7fd40bf31640]   (active)>",
    "<NSLayoutConstraint:0x600001845d60 'UISV-spacing' H:[_UIButtonBarButton:0x7fd40bf31640]-(0)-[UIView:0x7fd40bf31fe0]   (active)>",
    "<NSLayoutConstraint:0x600001845db0 'UISV-spacing' H:[UIView:0x7fd40bf31fe0]-(0)-[UIView:0x7fd40bd34f80]   (active)>",
    "<NSLayoutConstraint:0x600001845e00 'UISV-spacing' H:[UIView:0x7fd40bd34f80]-(0)-[UIView:0x7fd40bf32140]   (active)>",
    "<NSLayoutConstraint:0x600001845e50 'UISV-spacing' H:[UIView:0x7fd40bf32140]-(0)-[_UIButtonBarButton:0x7fd40bf322a0]   (active)>",
    "<NSLayoutConstraint:0x60000182fb60 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x6000002642a0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7fd40bd36200 )>",
    "<NSLayoutConstraint:0x60000182fc00 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x6000002642a0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7fd40bd36200 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600001845540 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fd40bf332a0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7fd40bf322a0 )>`

**Comment by vladborovtsov** [comment] 2019-09-25 08:38
indeed, simulator reboot fixes for some time.

**Comment by hackiftekhar** [comment] 2019-09-25 14:34
This looks to be a duplicate of #1592 and already addressed. I'm not 100% sure that this issue is fixed, but most of them will not get these issues. New version v6.5.0 will release soon.

**Closed by hackiftekhar** 2019-09-25 14:34 UTC

**Comment by mitalskhandhar** [comment] 2019-10-16 10:07
I am getting same issue in iOS 13 simulator my Ui get stuck while try to enter in TextField

**Comment by tanand7** [comment] 2019-10-22 12:53
I'm using the v6.5.1. having same issue. App gets stuck when keyboard opens.

**Comment by iadwait** [comment] 2020-11-12 06:25
I also faced same issue.
Do 1 thing Click on text field tool bar appears.
than go to hardware -> Toggle software Keyboard 2 times it worked.(On all Devices)
I have a doubt whether it will work on real device.
