### ISSUE TITLE
KeyboardDistanceFromTextField leads to wrong contentInset

### ISSUE THREAD

**Issue by Alarson93** [hackiftekhar/IQKeyboardManager#441] opened 2016-02-23 17:07 UTC
In my app delegate, I have the following line:
`[[IQKeyboardManager sharedManager] setKeyboardDistanceFromTextField:100];`

When I click on a textfield, it indeed respects this distance of 100. Unfortunately, there is now a 100 point gap at the bottom of the table when the keyboard is displayed (you won't notice it until you scroll to the bottom). The following image from your demo illustrates this point (make note of the location of the scroll indicator).
![simulator screen shot feb 23 2016 10 54 38 am](https://cloud.githubusercontent.com/assets/16312918/13259300/627dd9b8-da1c-11e5-839f-0cfb59ddc45c.png)

I'd imagine that the bottom inset should be the height of the keyboard and the offset should reflect the distance I have specified. For the time being I can use a distance of 0 or use drag to dismiss, but I'd like to bring this issue to your attention.

Thank you.

**Comment by hackiftekhar** [comment] 2016-05-16 15:55
It looks like duplicate of #496, #487, #485 Probably 28b2d9c0ee8169bd6c4cc3dfbdca8f272d059f7c commit fixed your issue.

**Closed by hackiftekhar** 2016-05-16 15:55 UTC
Labels: Need Investgation
