### ISSUE TITLE
Xcode 11 IQToolbar constraint issue.

### ISSUE THREAD

**Issue by gbk94** [hackiftekhar/IQKeyboardManager#1607] opened 2019-09-25 11:17 UTC
In Xcode 11 when the keyboard appeared I get "Unable to simultaneously satisfy constraints.".
It was working fine before Xcode 11. I had the same issue with my pickerview toolbar. I fixed it by simply specifying frame of my toolbar.

let toolBar = UIToolbar(frame: CGRect(x: 0, y: 0, width: view.frame.size.width, height: 35))

I tried to fix it in IQKeyboardManager, but I could not.

`[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x2819ee7b0 h=--& v=--& _UIToolbarContentView:0x137e13ce0.width == 0   (active)>",
    "<NSLayoutConstraint:0x2819a0af0 H:|-(0)-[_UIButtonBarStackView:0x137e172e0]   (active, names: '|':_UIToolbarContentView:0x137e13ce0 )>",
    "<NSLayoutConstraint:0x2819a1270 _UIButtonBarStackView:0x137e172e0.trailing == _UIToolbarContentView:0x137e13ce0.trailing   (active)>",
    "<NSLayoutConstraint:0x2819ed450 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x13c25f390'Done']   (active, names: '|':_UIButtonBarButton:0x13c25f1c0 )>",
    "<NSLayoutConstraint:0x2819ed4a0 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x13c25f390'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x13c25f1c0 )>",
    "<NSLayoutConstraint:0x2819edb80 'UISV-canvas-connection' UILayoutGuide:0x2803949a0'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x13c25dde0.leading   (active)>",
    "<NSLayoutConstraint:0x2819edbd0 'UISV-canvas-connection' UILayoutGuide:0x2803949a0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x13c25f1c0.trailing   (active)>",
    "<NSLayoutConstraint:0x2819edc20 'UISV-spacing' H:[_UIButtonBarButton:0x13c25dde0]-(0)-[UIView:0x13c25e570]   (active)>",
    "<NSLayoutConstraint:0x2819edc70 'UISV-spacing' H:[UIView:0x13c25e570]-(0)-[_UIButtonBarButton:0x13c25e6d0]   (active)>",
    "<NSLayoutConstraint:0x2819edcc0 'UISV-spacing' H:[_UIButtonBarButton:0x13c25e6d0]-(0)-[UIView:0x13c25ef00]   (active)>",
    "<NSLayoutConstraint:0x2819edd10 'UISV-spacing' H:[UIView:0x13c25ef00]-(0)-[UIView:0x137e11c90]   (active)>",
    "<NSLayoutConstraint:0x2819edd60 'UISV-spacing' H:[UIView:0x137e11c90]-(0)-[UIView:0x13c25f060]   (active)>",
    "<NSLayoutConstraint:0x2819eddb0 'UISV-spacing' H:[UIView:0x13c25f060]-(0)-[_UIButtonBarButton:0x13c25f1c0]   (active)>",
    "<NSLayoutConstraint:0x2819a3250 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x2803949a0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x137e172e0 )>",
    "<NSLayoutConstraint:0x2819a0b90 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x2803949a0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x137e172e0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2819ed4a0 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x13c25f390'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x13c25f1c0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.`

**Comment by hackiftekhar** [comment] 2019-09-26 05:53
Possible duplicate of #1592

**Comment by shravanteegala** [comment] 2019-09-30 18:33
Iam facing same issue

**Comment by hackiftekhar** [comment] 2019-10-21 12:38
It has already been fixed, it was related to the toolbar.

**Closed by hackiftekhar** 2019-10-21 12:38 UTC

**Comment by manish-1988** [comment] 2019-12-25 23:26
In Swift I am still facing this issue

**Comment by ElSawyMohamed** [comment] 2020-01-06 11:13
any solution ?
