### ISSUE TITLE
NavigationBar still moving with "scrollView trick"

### ISSUE THREAD

**Issue by RGSmithSoftware** [hackiftekhar/IQKeyboardManager#168] opened 2015-02-10 20:57 UTC
![test](https://cloud.githubusercontent.com/assets/4758815/6136148/e98f1e02-b133-11e4-84c3-635490f0f34f.gif)

Using pod v3.2.1.0

SETUP:
1. Basic single view application project with an UINavigationController.
2. Did "scrollView trick" to make NavigationBar not move
3. First TextField origin {8 , 119}
4. Second TextField origin {8 , 157}
4. Third TextField origin {8 , 253}

Any help on this will be nice:)

**Comment by hackiftekhar** [comment] 2015-02-11 05:21
Could you please test it with latest source code on repo not via cocoapods, I'm about to update cocoapods version? If still problem exist i'll look into this.

**Comment by RGSmithSoftware** [comment] 2015-02-11 05:39
I just did a retry with your recommendation, but I'm still receiving the problem.

**Comment by hackiftekhar** [comment] 2015-02-11 18:24
Could you please share demo code, so I can findout where the problem is.

**Comment by hackiftekhar** [comment] 2015-02-12 17:31
It seems there is still UIView behind textField, not a UIScrollView. Could you please confirm that all the textField is inside UIScrollView? How about 'Navigation Bar' section in IQKeyboardManager demo project?

**Comment by hackiftekhar** [comment] 2015-02-15 20:48
Any updates or demo project on this?

**Comment by hackiftekhar** [comment] 2015-02-17 17:06
Please provide a demo project to debug it otherwise the issue will be closed by assuming you've solve the issue.

**Comment by RGSmithSoftware** [comment] 2015-02-17 19:01
ok ill provide i demo today

**Comment by hackiftekhar** [comment] 2015-02-17 20:07
ok, thanks :)

**Comment by hackiftekhar** [comment] 2015-02-18 19:58
Have you ready with the demo app?

**Comment by RGSmithSoftware** [comment] 2015-02-18 20:40
Sorry, it seems I can’t find the original demo and I don’t have the time to devote to this issue anymore, I think it should be closed now.

**Comment by hackiftekhar** [comment] 2015-02-19 08:06
Due to your request, I'm closing this issue now. But I'm still worried about the issue. In near future, If you found the original demo app, you can also share then, I'm always here to fix the issues.

**Closed by hackiftekhar** 2015-02-19 08:06 UTC

**Comment by damirstuhec** [comment] 2016-09-09 10:04
Having the same issue.

**Comment by hackiftekhar** [comment] 2016-09-09 14:56
Please share demo, also please be sure that your scrollView has correct contentOffset.

**Comment by damirstuhec** [comment] 2016-09-09 18:27
The issue was that the height of the root content/container view inside the `UIScrollView` was too small. Looks like there is some logic depending on this height in some way. I fixed it by constraining that view to have full height of the `UIScrollView`.

**Comment by hackiftekhar** [comment] 2016-09-09 18:43
Yeah, the height is also considered with the algorithm I wrote.

**Comment by damirstuhec** [comment] 2016-09-27 14:18
@hackiftekhar I just had the same issue in table view as well. Running version `4.0.5`, Xcode 7, iOS 9.

The issue occurs if the content size of the table view is not high enough. In that case, I have to add empty footer view to expand the tableview and therefore "fill up" the parent view. Seem like there is some issue when the content is not high enough.

**Comment by damirstuhec** [comment] 2016-09-27 14:42
@hackiftekhar The funny thing is that everything works well if I use `Next` button on keyboard, but if I focus on text field directly, then the keyboard covers the text field.
