### ISSUE TITLE
Crash on IQKeyboardManager.swift:1197

### ISSUE THREAD

**Issue by cloud-hot** [hackiftekhar/IQKeyboardManager#183] opened 2015-03-23 14:09 UTC
Hi,

When i used the IQKeyboardManager under the ios8.2 swift environment there was a crash, log as follow: 

```bash
Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x00000001978580b4 objc_retain + 20
1  wifi-everywhere-personal       0x00000001000b9e34 wifi_everywhere_personal.IQKeyboardManager.(addToolbarIfRequired in _34772391F39F5C2187B6CFFAACB4690D) (wifi_everywhere_personal.IQKeyboardManager)() -> () (IQKeyboardManager.swift:1197)
2  wifi-everywhere-personal       0x00000001000b63f0 wifi_everywhere_personal.IQKeyboardManager.textFieldViewDidBeginEditing (wifi_everywhere_personal.IQKeyboardManager)(ObjectiveC.NSNotification) -> () (IQKeyboardManager.swift:902)
3  CoreFoundation                 0x0000000187200434 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
4  CoreFoundation                 0x000000018713f7e0 _CFXNotificationPost + 2060
5  Foundation                     0x00000001880376c0 -[NSNotificationCenter postNotificationName:object:userInfo:] + 72
6  UIKit                          0x000000018badeb20 -[UITextField _becomeFirstResponder] + 616
7  UIKit                          0x000000018ba5da8c -[UIResponder becomeFirstResponder] + 392
8  UIKit                          0x000000018ba5de10 -[UIView(Hierarchy) becomeFirstResponder] + 124
9  UIKit                          0x000000018badd4e8 -[UITextField becomeFirstResponder] + 68
10 UIKit                          0x000000018bb8e288 -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessary] + 200
11 UIKit                          0x000000018bb8d8f0 -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) oneFingerTap:] + 1736
12 UIKit                          0x000000018bb73768 _UIGestureRecognizerSendActions + 276
13 UIKit                          0x000000018ba0c184 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 580
14 UIKit                          0x000000018be74f78 ___UIGestureRecognizerUpdate_block_invoke662 + 60
15 UIKit                          0x000000018b9d075c _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 292
16 UIKit                          0x000000018b9ceb08 _UIGestureRecognizerUpdate + 2504
17 UIKit                          0x000000018ba0a32c -[UIWindow _sendGesturesForEvent:] + 1044
18 UIKit                          0x000000018ba099cc -[UIWindow sendEvent:] + 660
19 UIKit                          0x000000018b9dd1d4 -[UIApplication sendEvent:] + 264
20 UIKit                          0x000000018bc7b98c _UIApplicationHandleEventFromQueueEvent + 14992
21 UIKit                          0x000000018b9db73c _UIApplicationHandleEventQueue + 1616
22 CoreFoundation                 0x0000000187212324 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
23 CoreFoundation                 0x00000001872115c8 __CFRunLoopDoSources0 + 264
24 CoreFoundation                 0x000000018720f678 __CFRunLoopRun + 712
25 CoreFoundation                 0x000000018713d664 CFRunLoopRunSpecific + 396
26 GraphicsServices               0x000000019027f5a4 GSEventRunModal + 168
27 UIKit                          0x000000018ba424f8 UIApplicationMain + 1488
28 wifi-everywhere-personal       0x0000000100194170 main (AppDelegate.swift:14)
29 libdyld.dylib                  0x0000000197eaea08 start + 4
```

Hope you could help me! Thanks!

**Comment by hackiftekhar** [comment] 2015-03-25 16:38
Hi,
  I'll debug it and let you know my feedback.

**Comment by cloud-hot** [comment] 2015-03-26 11:49
Thanks! If you need any information please let me know!

**Comment by hackiftekhar** [comment] 2015-04-19 21:08
Hi,
  I tried to reproduce the issue, but unfortunately I'm not able to reproduce it. If you can send me sample code and steps to reproduce issue, then it would be best for me.

**Comment by hackiftekhar** [comment] 2015-04-21 20:57
@cloud-hot , are you still getting issues with this? As of Swift 1.2 (Xcode 6.3), Apple fixes many LLVM compiler issues, so may be it is resolved already, but still need your confirmation.

**Comment by hackiftekhar** [comment] 2015-04-27 07:54
@cloud-hot  Any updates?

**Comment by cloud-hot** [comment] 2015-05-03 15:14
Hi @hackiftekhar ,

I am very sorry for reply so later, After i change the compiler flag this problem is disappeared following the instruction on your README. So it seems that this problem is caused by Xcode version.

And because my project has not updated to Xcode6.3 so i am not sure this problem is solved on Xcode6.3

**Comment by hackiftekhar** [comment] 2015-05-03 18:07
@cloud-Hot Could you please test it with Xcode 6.3 and let me know your feedback.

**Comment by cloud-hot** [comment] 2015-05-03 23:31
Hi Hackiftekhar,

OK, i will try my best to find the time to do the test. But recently my project plan is very tight, sorry for reply not so quickly

Wenjie
Best Regards

**Comment by hackiftekhar** [comment] 2015-05-10 18:44
Any updates?

**Comment by cloud-hot** [comment] 2015-05-12 15:46
Hi Hackiftekhar,

Until now our project has not upgraded to the latest Xcode6.3. And if we upgraded to Xcode6.3 we will have lots of adoption to do, so now i have no idea about whether this issue will disappear on the latest Xcode6.3, sorry for that.

**Comment by hackiftekhar** [comment] 2015-05-12 16:15
You can copy your whole project to a temporary location and test on that. It will help me to take appropriate action on this github issue.

**Comment by cloud-hot** [comment] 2015-05-12 23:51
ok，could you help me a temporary location which you have access?

**Comment by hackiftekhar** [comment] 2015-05-13 04:27
I mean you can copy your whole project to your desktop(temporary location) and test on it. You don't need to share your code with me, it's confidential thing for you.

**Comment by cloud-hot** [comment] 2015-05-13 14:20
Hi Hackiftekhar,

Sorry, i have tried to compile our project using the Xcode6.3 but there are so many complier error and i try to fix it but it failed. So recently i am afraid i can not make sure to try it using the Xcode6.3.

**Comment by hackiftekhar** [comment] 2015-05-13 15:49
Ok, so let me know if you want to test it n near future so that I'll keep issue open, otherwise will close it.

**Comment by cloud-hot** [comment] 2015-05-13 23:45
Hi Hackiftekhar,

I am not sure when i can test it on the Xcode6.3. I suggest that you can close it now and then if i found there is still issue then re-open it

**Comment by hackiftekhar** [comment] 2015-05-14 12:14
Thanks :)

**Closed by hackiftekhar** 2015-05-14 12:14 UTC
Labels: bug
