### ISSUE TITLE
Compile error on 6.4.0 statusBarOrientationUserInfoKey

### ISSUE THREAD

**Issue by catach** [hackiftekhar/IQKeyboardManager#1573] opened 2019-07-02 20:07 UTC
**Describe the bug**

Swift compile error on this line:

> IQKeyboardManager.swift:1861:79: 'statusBarOrientationUserInfoKey' has been renamed to 'UIApplicationStatusBarOrientationUserInfoKey'

**To Reproduce**
Just compile it 

**Expected behavior**
No compilation errors

### Versions
**Xcode:** 10.2.1
**Mac OS:** 10.14.5
**Simulator/Device:** n/a
**Simulator/Device Name:** n/a
**Library Version:** 6.4.0

**Comment by hackiftekhar** [comment] 2019-07-05 03:37
Which swift version you are using? I'm unable to reproduce this with Xcode 10.2 and Xcode 11 beta. I'm not sure about Xcode 10.2.1.

**Comment by myphproad** [comment] 2019-07-30 07:57
statusBarOrientationUserInfoKey---> UIApplicationStatusBarOrientationUserInfoKey

**Comment by hackiftekhar** [comment] 2019-08-01 15:12
This is now fixed with v6.4.1

**Comment by catach** [comment] 2019-08-01 19:59
@hackiftekhar you were right, I was using 4.0 to compile

```ruby
    installer.pods_project.targets.each do |target|
        if target.name == 'IQKeyboardManagerSwift'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
```

**Closed** 2019-08-01 19:59 UTC

**Comment by hackiftekhar** [comment] 2019-08-10 22:47
Yes. You are correct! I'll add it in issue checklist.
