### ISSUE TITLE
enabledDistanceHandlingClasses is noneffective

### ISSUE THREAD

**Issue by zzyspace** [hackiftekhar/IQKeyboardManager#604] opened 2016-08-11 06:53 UTC
I set `enable` to `NO` in AppDelegate:
```objc
// AppDelegate.m
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [IQKeyboardManager sharedManager].enable = NO;
    return YES;
}
```
and then add `HWAddressDetailController` to `enabledDistanceHandlingClasses` in `viewDidLoad`:
```objc
// HWAddressDetailController.m
- (void)viewDidLoad {
    [super viewDidLoad];
    [[[IQKeyboardManager sharedManager] enabledDistanceHandlingClasses] addObject:[self class]];
}
```
but it doesn't work..

**Comment by zzyspace** [comment] 2016-08-11 07:28
With breakpoint, I found that `UIViewController *textFieldViewController = [_textFieldView viewController];` in `-(BOOL)privateIsEnabled` always nil because following method never be called:
```objc
-(UIViewController*)viewController
{
    UIResponder *nextResponder =  self;
    
    do
    {
        nextResponder = [nextResponder nextResponder];

        if ([nextResponder isKindOfClass:[UIViewController class]])
            return (UIViewController*)nextResponder;

    } while (nextResponder != nil);

    return nil;
}
```
I think the '- viewController' method might be overrided in other UIView category in my project but I can't find yet. I suggest you can add prefix for every method in categories with your lib.

**Comment by zzyspace** [comment] 2016-08-11 07:55
I resovle this problem by adding prefix for `viewController` property:
```objc
// IQUIView+Hierarchy.h
@property (nullable, nonatomic, readonly, strong) UIViewController *iq_viewController;

// IQUIView+Hierarchy.m
-(UIViewController*)iq_viewController
{
    UIResponder *nextResponder =  self;
    
    do
    {
        nextResponder = [nextResponder nextResponder];

        if ([nextResponder isKindOfClass:[UIViewController class]])
            return (UIViewController*)nextResponder;

    } while (nextResponder != nil);

    return nil;
}
```

**Comment by hackiftekhar** [comment] 2016-08-11 15:09
Hmm, not sure but looks like there some other lib override the category method

**Comment by zzyspace** [comment] 2016-08-11 16:31
Yeah, finally I find `viewController` method with another framework. I have forked your project and add prefix for categories. I'll pr tomorrow. By the way, IQKeyboardManager is really a fantastic lib~

**Comment by hackiftekhar** [comment] 2016-08-11 19:24
Thanks, Now I think I should prefix some other methods too whose names are commonly used by other libs too.. Don't worry I'll do that myself. Thanks for pointing out.

**Comment by hackiftekhar** [comment] 2016-10-20 18:14
Duplicate of #595 where I already provide my feedback today.

**Closed** 2016-10-20 18:14 UTC
Labels: enhancement
