### ISSUE TITLE
Device Orientation

### ISSUE THREAD

**Issue by fahlout** [hackiftekhar/IQKeyboardManager#274] opened 2015-08-25 19:16 UTC
I found one more bug. It seems like you are using device orientation, which does not guarantee either landscape or portrait only. If it is face up or face down, keyboard manager will not know if the device is portrait or landscape and the frame will be wrong. Use status bar orientation to know if it is portrait or landscape even when the device is face up or face down.

**Comment by hackiftekhar** [comment] 2015-08-27 07:43
@fahlout I'm using `InterfaceOrientation` to determine `UIViewController orientation`.

There are differences between `UIDeviceOrientation` and `UIInterfaceOrientation`.

`UIDeviceOrientation` tell's the actual device orientation with respect to the earth gravity
    UIDeviceOrientationUnknown,
    UIDeviceOrientationPortrait, 
    UIDeviceOrientationPortraitUpsideDown, 
    UIDeviceOrientationLandscapeLeft,
    UIDeviceOrientationLandscapeRight,
    UIDeviceOrientationFaceUp,
    UIDeviceOrientationFaceDown,

But `UIInterfaceOrientation` has no relation with earth gravity. It just tells us the UIViewController orientation with respect to device. And you know there are no Face-Up and Face-Down orientation with UIInterfaceOrientation.
    UIInterfaceOrientationUnknown
    UIInterfaceOrientationPortrait
    UIInterfaceOrientationPortraitUpsideDown
    UIInterfaceOrientationLandscapeLeft
    UIInterfaceOrientationLandscapeRight

**Comment by fahlout** [comment] 2015-08-27 18:28
That is correct. Doing size calculations on UIDeviceOrientation is bad though and very error prone as you don't necessarily know if it is in portrait or landscape and can therefore not calculate the right size for the toolbar. I have just seen the toolbar being in landscape dimensions when the device was in portrait and I am guessing it is because UIDeviceOrientation is used instead of UIInterfaceOrientation

**Comment by hackiftekhar** [comment] 2015-08-27 20:08
If you get toolbar dimentions like landscape but yiu are in portrait, just share demo and I'll look the cause for that. Thanks

**Comment by hackiftekhar** [comment] 2015-09-07 09:01
Do you have any updates regarding demo project?

**Comment by hackiftekhar** [comment] 2015-10-13 12:23
Do you have any updates regarding the issue or should I close this issue?

**Closed** 2015-10-22 12:03 UTC
Labels: Demo Requested, question
