### ISSUE TITLE
not working in iOS11 

### ISSUE THREAD

**Issue by mohsinalimat** [hackiftekhar/IQKeyboardManager#962] opened 2017-09-08 12:38 UTC
Hello,

When i set textfield as a secure password field than password autofill quicktype bar in iOS11 

Keyboard with password autofill quicktype bar cover my textfield...

**Comment by donaldyang** [comment] 2017-09-11 01:52
I found it don't work on iOS11 too.But it can pack up the keyboard when i touch right top position where have not button.

**Comment by hackiftekhar** [comment] 2017-09-22 13:01
I tried checking with my demo and it works well for me. Can you please provide gif and/or demo project to debug it?

**Comment by pgawlowski** [comment] 2017-09-28 12:28
@hackiftekhar I've got quite the same issue. On screen I tapped e-mail textField. Keyboard i being initialized and quicktype is being generated AFTER keyboard is visible. This action takes e-mail textField under keyboard toolbar. 

The problems seems to not appear when you move up&down with arrows after first init of keyabord (in that case keyboard somehow remember quicktype value) and keyboard avoiding know how to handle.

![img_0529](https://user-images.githubusercontent.com/9845024/30966353-e60568b6-a458-11e7-9b25-8a497d683080.jpg)

**Comment by hackiftekhar** [comment] 2017-09-28 13:02
hmm, okay @pgawlowski I'll check what might be the issue.

**Comment by pgawlowski** [comment] 2017-10-01 12:22
@hackiftekhar - I can provide video or code sample for this, but I'd prefer to keep it on private in that case.

**Comment by hackiftekhar** [comment] 2018-03-12 18:04
@pgawlowski Can you please provide a demo code here which might not related to your main project but related to this issue?

**Comment by hackiftekhar** [comment] 2018-06-15 10:13
Looks like this issue isn't reproducible with latest version. Closing. In case if this still reproducible then don't hesitate to reopen this.

**Closed by hackiftekhar** 2018-06-15 10:13 UTC
