### ISSUE TITLE
SEGV_ACCERR

### ISSUE THREAD

**Issue by hardyZhi** [hackiftekhar/IQKeyboardManager#583] opened 2016-07-27 09:27 UTC
0 libobjc.A.dylib	objc_msgSend + 28
1 UIKit	-[UIScrollView(UIScrollViewInternal) _notifyDidScroll] + 72
2 UIKit	-[UIScrollView setContentOffset:] + 500
3 UIKit	-[UIAnimator(Static) _advanceAnimationsOfType:withTimestamp:] + 316
4 QuartzCore	CA::Display::DisplayLinkItem::dispatch() + 32
5 QuartzCore	CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 324
6 IOKit	IODispatchCalloutFromCFMessage + 376
7 CoreFoundation	___CFMachPortPerform + 180
8 CoreFoundation	___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
9 CoreFoundation	___CFRunLoopDoSource1 + 436
10 CoreFoundation	___CFRunLoopRun + 1640
11 CoreFoundation	CFRunLoopRunSpecific + 396
12 GraphicsServices	GSEventRunModal + 168
13 UIKit	UIApplicationMain + 1488
14 Loan	0x000000010002c000 + 237840
15 libdyld.dylib	_start + 4

**Comment by hardyZhi** [comment] 2016-07-27 09:28
IQKeyboardManager v3.3.7

**Comment by hackiftekhar** [comment] 2016-07-27 10:57
How can you sure that it's related to library. By seeing crash logs, I'm not sure if this is due to library because there is no info related to library.

**Comment by hardyZhi** [comment] 2016-07-28 02:44
In my project,only this library use setContentOffset.

**Comment by hackiftekhar** [comment] 2016-07-28 06:51
Please provide demo, I'm not sure why this crash happens.

**Comment by hardyZhi** [comment] 2016-07-29 01:27
I can't reproduce this crash,only get this crash in a analysis platform,so i can't provide demo to reproduce this crash.

**Comment by hackiftekhar** [comment] 2016-07-29 05:13
Closing this issue because of following reason:
- according to crash logs, it doesn't look like library issue.
- There is no demo project because it isn't reproducible.

**Closed by hackiftekhar** 2016-07-29 05:13 UTC
Labels: Demo Requested
