### ISSUE TITLE
iPhone app launch on iPad, the keyboard cover the textfield, is that bug?

### ISSUE THREAD

**Issue by luoshihui** [hackiftekhar/IQKeyboardManager#1139] opened 2017-11-17 09:23 UTC
![img_0303](https://user-images.githubusercontent.com/4970812/32939830-76069458-cb46-11e7-9d65-0cd498a5f4ac.PNG)
![img_0304](https://user-images.githubusercontent.com/4970812/32939837-791245b6-cb46-11e7-9b67-a8cbea2d7bc1.PNG)
![img_0305](https://user-images.githubusercontent.com/4970812/32939842-7acf1f6e-cb46-11e7-8aaf-30b4a87c14a9.PNG)

see the attaching images,
iPhone app launch on iPad(ios 11, but i think it has nothing with the os version), the keyboard cover the textfield, is that bug?
And on iphone 4s (ios 9.3.5) is good. also other iphones are good.

**Comment by iMishaDev** [comment] 2017-11-17 13:50
the same here. I can't even hide the keyboard when I click on RETURN button.

**Comment by hackiftekhar** [comment] 2018-03-14 13:53
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Closed by hackiftekhar** 2018-03-14 13:53 UTC

**Comment by iOSUser110** [comment] 2018-05-23 13:54
Facing this issue in the latest release , and apple rejected my iPhone app , because of iPhone resolution app on iPad keyboard covers textfield. Required solution ASAP ...please reply

**Comment by iOSUser110** [comment] 2018-05-24 05:49
HI @hackiftekhar , I have used  " pod 'IQKeyboardManagerSwift' " in podfile
and just add the below code line in appDelegate didFinish
IQKeyboardManager.shared.enable = true

nothing more than that , still you require demo code and screenshot i can share, please let me know

**Comment by hackiftekhar** [comment] 2018-05-24 09:11
I think demo would be better since sometimes it reproduce on your main app due to some other issues and might now be reproducible in demo app.
