### ISSUE TITLE
Bluetooth headphones put into "Call mode"

### ISSUE THREAD

**Issue by oliverfoggin** [hackiftekhar/IQKeyboardManager#770] opened 2017-02-10 12:52 UTC
I have no idea why yet but I have narrowed it down to this framework.

When I'm on the simulator and access the software keyboard when my bluetooth heaphones (Bose QC35) are connected to my laptop it switches them into "call mode" and it doesn't turn off without disconnecting bluetooth from my laptop.

I haven't narrowed it down yet to the code but it shouldn't really be going anywhere near the bluetooth sound stuff.

Thanks

**Comment by hackiftekhar** [comment] 2017-02-22 03:37
I don't think it's related to IQKeyboardManager,

**Comment by oliverfoggin** [comment] 2017-02-22 06:42
That's what I would think also. But it only happens on the simulator and only when I'm using this framework. LOL :)

**Comment by Benuuu** [comment] 2017-02-27 22:03
@oliverfoggin I believe I'm observing this behavior too.  I was able to create a simple project with a text field and IQKeyboardManager. Tap into the text field then tap the "Done" button on the accessory view.  This was enough to reproduce the issue I'm seeing

**Comment by oliverfoggin** [comment] 2017-02-27 22:06
I found a way to turn it off. It appears to be setting the computers microphone input to be the headphones. Not sure how yet but you can go into sound settings and input devices and it will have selected the headphones.

**Comment by oliverfoggin** [comment] 2017-02-27 22:07
@Benuuu ^

**Comment by Benuuu** [comment] 2017-02-27 22:09
@oliverfoggin did you trace down why it was trigging any change?

**Comment by oliverfoggin** [comment] 2017-02-27 22:10
@Benuuu the current project I'm on we're not using his framework so haven't had time to look into it.

**Comment by Benuuu** [comment] 2017-02-27 22:11
[[UIDevice currentDevice] playInputClick];

Is triggering it

**Comment by Benuuu** [comment] 2017-02-27 22:20
This appears to be an Apple bug.  A simple VC will reproduce it:


`import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var textField: UITextField!

    override func viewDidLoad() {
        super.viewDidLoad()
        let button = InputView(frame: CGRect(x: 0, y: 0, width: 320, height: 50))
        button.backgroundColor = UIColor.red
        button.addTarget(self, action: #selector(buttonTapped), for: .touchUpInside)
        textField.inputAccessoryView = button
    }

    func buttonTapped() {
        UIDevice.current.playInputClick()
    }
}

class InputView: UIButton, UIInputViewAudioFeedback {
    var enableInputClicksWhenVisible: Bool { return true }
}
`

**Comment by Benuuu** [comment] 2017-02-27 22:35
Filed radar: 30742803

**Comment by hackiftekhar** [comment] 2017-04-01 17:34
I think it's better to close this issue since it doesn't related to library and related to playInputClick() method.

**Closed by hackiftekhar** 2017-04-01 17:34 UTC
Labels: iOS Bug/Limitation
