### ISSUE TITLE
iOS11 keyboard manager gesture recognizer confilcts with table view didSelect

### ISSUE THREAD

**Issue by linarchabibulin** [hackiftekhar/IQKeyboardManager#1041] opened 2017-10-04 09:15 UTC
Hi, I came across this kind of bug introduced by iOS11

1) On lower versions everything works
2) shouldResignOnTouchOutside is set to true
3) Using swift if it matters
4) Example: I do have location picker (it is UITextField with UITableView attached to it), when I start writing something into textfield, the tableView with suggestions get shown below textfield. If I try to to tap on the suggestion - the table view didSelect method does not get triggered. Instead keyboardManager `tapGesture` is triggered.
5) When I am clicking the suggestion I do it very quickly and very lightly. If I press it longer/more firmly tableView delegate didSelect method gets triggered. But I cannot tell customer: "I will not do anything, just press that button harder" :D
6) Setting `touchResignedGestureIgnoreClasses` parameter to "UITableView or UITableViewCell" will not work because `touch.view`, that we are checking is of class `UITableViewCellContentView` (this class is not accessible, so I can not add it to `touchResignedGestureIgnoreClasses`)
7) I needed a quick fix, so what I did I added new parameter `touchResignedGestureIgnoreInstanceList` - list of UIViews. In the `gestureRecognizer:shouldReceive:` method I am checking that list if `touch.view` `isDescendant` of an instance. Off course I had to set and cleanup `touchResignedGestureIgnoreInstanceList` on `viewWillAppear` and `viewWillDisappear` accordingly not to break anything. 

Actually it would be a nice feature to be able to ignore certain instance of a view, not all views of certain type.

**Comment by hazemmaher92** [comment] 2017-10-05 08:55
same exact issue here

**Comment by hackiftekhar** [comment] 2017-10-12 16:33
I checked mentioned issue with my demo application but I found that both methods are properly called. But even if this is an issue then I cannot implement a generic solution because library shouldn't accept instances of any classes that are view controller based. However you should disable touch resigning for that particular view controller if you can, that would be a better solution i believe.

**Comment by linarchabibulin** [comment] 2017-10-12 16:44
Hi hackiftekhar,
thanks for reply, I agree that library should not have anything to do with instances. I just mentioned that as quick hacky workaround for people to use at their own risk.
Unfortunately I cannot disable touch resigning for that particular view controller.
At some point later I could add some demo project to reproduce the issue.

**Comment by linarchabibulin** [comment] 2017-10-30 12:10
Hi @hackiftekhar ,
I have created the example project to just to recreate my described issue:
https://github.com/linarchabibulin/KeyboardManagerIssueExample

It happens when:
we click on top textfield -> keyboard and tableView appears -> if we select a tableView cell (perform very light click) the keyboard and tableView get hidden, but didSelect method does not get called. Off course if we press more firmly on tableView it gets selected. 

Feel free to close the issue if you think this is not an issue or cannot be fixed in any proper way.

**Comment by hackiftekhar** [comment] 2017-11-04 08:59
Thanks @linarchabibulin for providing the demo project, I'll keep it open at least till I check your demo project.

**Comment by anilabsinc-ajay** [comment] 2017-11-13 05:54
Facing Same issue

**Comment by NBibikov** [comment] 2018-03-01 10:12
Please, check this issue 😢

**Comment by hackiftekhar** [comment] 2018-03-15 14:35
I checked @linarchabibulin I found that you are hiding tableView in `textFieldDidEndEditing` delegate method. The problem is that your tableView get's hidden before moving to it's delegate call. If you comment that line then it will surely work.

**Closed by hackiftekhar** 2018-03-15 14:35 UTC
